### ISSUE TITLE
Pile of errors 

### ISSUE THREAD

**Issue by pennybox** [pygnode/Battle-Royale#1]
![image](https://user-images.githubusercontent.com/39643640/69905770-57958080-136d-11ea-9c7e-080e0cac51d4.png)

![image](https://user-images.githubusercontent.com/39643640/69905771-5fedbb80-136d-11ea-9752-2e6a7fb1cee3.png)

![image](https://user-images.githubusercontent.com/39643640/69905772-6da34100-136d-11ea-809f-06adb1e2a94a.png)

**Comment by pygnode** [comment]
Hey @pennybox - Thanks for the report! What settings are you compiling with? I have seen this reported as well but cannot reproduce even if I create a fresh project. Did you create directories under `/Custom`  like repo has?

**Comment by pygnode** [comment]
Just pushed an update, can you try again please
