### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by pennybox** [pygnode/Battle-Royale#3]
![image](https://user-images.githubusercontent.com/39643640/69908482-1a9ead80-13b0-11ea-8779-691fc5618440.png)

**Comment by pennybox** [comment]
Revolve#2637

is my discord

**Comment by pygnode** [comment]
thank you for the reports, does this cause the scripts not to work? Warnings shouldn't!

**Comment by pennybox** [comment]
Well. when entering Battle Royal and walking around nothing happens. the phase does not start

**Comment by pennybox** [comment]
Please hit me up on discord to discuss a further fix.

**Comment by malexanderboyd** [comment]
Added

**Comment by pennybox** [comment]
get teleported to night havan then nothing happens.

**Comment by pygnode** [comment]
Currently it's setup to only start after 3 players have joined. Do you get a message saying you joined the queue to start?

**Comment by pygnode** [comment]
Added on discord.
