### ISSUE TITLE
[REQ] Move the script to AzerothCore

### ISSUE THREAD

**Issue by asfo** [pygnode/Battle-Royale#5]
Hey Pygnode, I think your script is amazing, today I found it but I wasn't able to test it since my server is running in AzerothCore, I tried to make it works, but since I'm pretty newbie with C++ and AC/TC core functionalities, I wasn't able to.

The first thing I see is that "GuidDeque" is not defined in AzerothCore...
Line #87 GuidDeque queue; 
File: battle_royal.h

Tried to find the definition but seems like TC use a file called ObjectGuid.h which doesn't exists in AzerothCore, I tried to add it to a file that looks like this ObjectGuid but didn't work...also in AzerothCore there is an issue with something about "virtual" and "overrides" in the "GossipHello" in Line #21 in file battle_royal_gamemaster.cpp

Those were the first issues I found, the "GossipHello" I tried to switch to the AzerothCore method, "sGossipHello" which is "virtual" (found in UnitAI.h) but the error becomes something about a return type.

And after like 2 hours fighting with this I just leave it because I'm really newbie and I hope you can find a way to do this in AzerothCore, I will try to test it for you if you want, we have a small amount of people (like 20~) but I will do my best to test this until we got it working if that helps, or I will do any other thing that you want from me so this can be "merged" with AzerothCore.

Hope there is a way, and if not, I really appreciate your basecode anyways, thanks!.

**Comment by pygnode** [comment]
Hey @asfo - Really appreciate the detailed request! I know a few issues you mentioned are around abstractions TrinityCore is providing (such as `GuidDeque`). 

While I haven't used AzerothCore before, I will try to get something set up locally to try and do the required refactors to handle both TrinityCore + AzerothCore without needing two separate versions.  Hopefully, I can provide an updated version for you to test out shortly.

**Comment by asfo** [comment]
> Hey @asfo - Really appreciate the detailed request! I know a few issues you mentioned are around abstractions TrinityCore is providing (such as `GuidDeque`).
> 
> While I haven't used AzerothCore before, I will try to get something set up locally to try and do the required refactors to handle both TrinityCore + AzerothCore without needing two separate versions. Hopefully, I can provide an updated version for you to test out shortly.

OMG, THAT'S AMAZING BRO! THANK YOU!...

Also, I will learn from you...really appreciate it!

**Comment by pygnode** [comment]
Hey @asfo - I've opened #6, but I'll need your help. I'm not able to get AzerothCore setup locally because their docker setup is broken (mysql 5.7 enables SSL by default which is broken on Ubuntu 20).

The current code was adjusted to match AzerothCores changes to the database and a few functions. If you can copy the `Battle_Royale` inside your `/modules` folder, everything should load correctly. You'll also need to run the insert statements under `Battle_Royale/sql/world/production.sql`.

If all goes well, I'll update the readmes and such to properly release it to the AzeorthCore module marketplace.

**Comment by pygnode** [comment]
Hey @asfo  - I've opened #6  as a WIP branch for the changes required for AzerothCore. 

If you have some time to test these (using branch `azerothcore-pr`) it would be really helpful. You should be able to copy the `Battle_Royale` folder into your `/modules/` directory. Once there, run the sql and compile.

Let me know how it turns out, and I can work on cleaning it up to publish.

**Comment by asfo** [comment]
@pygnode thanks bro! I will test it in an hour, just need to cleanup the core and will do! ... I'll let you know how it went, again, thanks! You're awesome

**Comment by asfo** [comment]
SQLs are okay! everything fine in that part.

The compilation is okay too! now it passes, it doesn't crash at start and everything looks okay for the code.

But the "Hercules" npc, doesn't talk, it just say "Greetings, %name%" (where the %name% is the real player name).

The quest NPC (Alexander) actually gives the quest (but, the item I don't know what is that), the other one actually sells some items (Kitano Nahara) but the "Items" just doesn't show anything 🤔 . 

Maybe the "Items" should be a "36 slots crate" title?, it gives me a crate. Or maybe control the items based on a table? 🤔 so we can add items in a table easily and without restart they are pulled.

SS of what the NPC says:
![image](https://user-images.githubusercontent.com/829964/93846861-eb249e80-fc6a-11ea-98f2-288519ebb62f.png)

Not sure if I did something wrong 🤔 but that is the thing I have right now and I wasn't able to test the BR since I was not able to enter to the queue :(

**Comment by pygnode** [comment]
Hey @asfo  - Thanks for testing! The quest required item is a `King's Badge, 69601` which is awarded to players who win the Battle Royale. It's 1 of 2 currencies of the Royale, the other being `Bloodshed Tokens, 69600` which are granted from a PvP kill.

I love the idea of moving the rewards into a database table, but that's out of scope for what I can make time for at the moment. However, it shouldn't be *too* bad to implement. You may need to delete the teleporter npc (`133701`) to get the teleport option to show up. If not, we can dig a bit deeper - you may want to search your core startup scripts for "Scripts" or "Battle_Royale" for any errors. Also, you can test the battle royale itself without the teleporter using `.teleport moonglade` 


I pushed some changes to hopefully resolve the following issues if you don't mind pulling and trying again:

- Fixed the Rewards Vendor (Kitano Nahara) when interacting with the items page, it properly displays now.


Thanks again

**Comment by asfo** [comment]
The item thing is fixed.

![image](https://user-images.githubusercontent.com/829964/93922818-15f90c00-fcd8-11ea-978b-a8996bf8e3dc.png)

The item from the quest is still bugged or something because I see this:

![image](https://user-images.githubusercontent.com/829964/93922958-4e98e580-fcd8-11ea-9197-3e4330a254d2.png)

![image](https://user-images.githubusercontent.com/829964/93923940-aedc5700-fcd9-11ea-90aa-df14b8154a12.png)


The error from the teleporter was a typo...

```
2020-09-22 13:32:52 Script named 'item_battle_royal_reward_title_champion' is not assigned in the database.
2020-09-22 13:32:52 Script named 'npc_battle_royale_teleporter' is not assigned in the database.
2020-09-22 13:32:53 Script named 'npc_battle_royal_teleporter' is assigned in the database, but has no code!
```
Maybe because I added the wrong SQL from TC before trying to test this, so my fault :P, I did the update and now is ready.

The message works weird (don't know why) in this case, I can see the winner message, but I can't see it from the loser:
![image](https://user-images.githubusercontent.com/829964/93924354-3a55e800-fcda-11ea-927d-000407818ee4.png)

Here from the loser:
![image](https://user-images.githubusercontent.com/829964/93924447-5d809780-fcda-11ea-8c5c-90b6c630a13e.png)

But, after the infection killed the loser, I see the message:

![image](https://user-images.githubusercontent.com/829964/93924765-c8ca6980-fcda-11ea-9df4-e852f935181c.png)

Also, maybe create a real aura? I can't see any aura, not sure if there is a way:
![image](https://user-images.githubusercontent.com/829964/93924862-f1526380-fcda-11ea-9051-ea0418d49350.png)


Here from the player point of view:
![image](https://user-images.githubusercontent.com/829964/93924914-00391600-fcdb-11ea-94a3-a921125526f0.png)

Also here the protection from the relic doesn't have any visible aura (debuff, not the shields):
![image](https://user-images.githubusercontent.com/829964/93925164-5c9c3580-fcdb-11ea-819a-faebc6adf9a8.png)

I win already one time, but the quest didn't complete
![image](https://user-images.githubusercontent.com/829964/93928962-bce1a600-fce0-11ea-8871-bf9e50bb4257.png)

When you use the item like a mount, this happens but never ends until you click on "Esc" and the item is never removed:
![image](https://user-images.githubusercontent.com/829964/93929133-03cf9b80-fce1-11ea-8b91-c856b23b68df.png)


Extra comments:

One thing that I noticed, is that some NPC can "attack" the players (were one case, don't know why in a human warlock being teleported after created), remove the TP from druids and close the entrance, maybe, don't know if this is possible, remove them if the "Battle royal enabled" option is set, so this place is protected and can be accessed only by using the NPC and the NPC should checks if the player is level 80 because one level 75 could join but is not fair to them, since its an open world, so just check for level 80s...

Another twerk could be that the first infection is actually doing too much damage, maybe start from 50-75~ in a "random way" and then increase by 10% every time or stack them.

Now, the healers in this way can go "AFK" for a moment, and then after don't know 3-4 infections get the relic and continue (like a druid going hidden). So, the infection should reduce heals at 50%. So they can't go AFK.

Now, the relic thing works pretty nice, but if there is only 1 place, everyone is forced to go there, then, starts the PvP in the same place and that's it, there is not too much strategy, so I think is better, maybe my ideal here, to add the 3 relics and show a message like "The relics are placed!" after 2 minutes or something (maybe add a configuration for the timers), if you click one of them, removes the aura and clean, so you have 2 minutes to "hide" or create a strategy again, and then check if you should go to X, Y or Z relic, and they can walk hidden, try to find rogues and stuff like that, and remove the relic after I don't know, 30 secs? so you need to stay close when the relic is going to show.

Or another thing that could work is that the first phase has the 3 relics, then 2, then 1 and keep 1 only like it works actually.

Also, place the people in random places in Moonglade maybe could be another option at the start...

Here come the "hidden people", so another twerk could be that if you get the infection you can't hide, so druids are not hiding and can't heal themselves until they "win".

The price from the tokens should be 1 copper or something, so they are being used as a token for the store only and not for gold 🤔 

Another thing is that if you win or lose or whatever you're being teleported to the same place where you start at level 1, maybe use something like the `.recall` command and tp them to the previous place?, or TP them where the NPC from the BR is, because for example, if I add the NPC in "X" Place, there could be a query to get the place and then recall the player there because the only way to go in is using it, so the recall is going to recall them there, but as an extra, this could have a command like `.joinbr` to join everywhere you're like a BG, and then if you lose, you get back to your place, that's why the `recall` thing

Finally, another twerk is that the chat shows "Battle starting in 10...9...8" so they know it is starting and when the relics are being moved away ("Relics blablabla in 10 seconds, get ready!" or something like this).

Actually the BR works great I loved it! but I was thinking in those weird cases and the aura is something that I think it should show as a debuff at least so we know that we have it or we have the protection (I know that it shows the shields, but its weird in my case to not know what is happening after that and when it started the infection).

For now, with 5 players, starts as intended, I don't know if there is a limit of players (I think it has one), finish if you disconnect and there is only 1, if 4 dies of the infection and there is only 1 left, the winner receives the token as intended and if you kill someone gives the other token too.

If I found any other issue, I will let you know, THANKS AGAIN!

**Comment by pygnode** [comment]
Thanks for all your comments.  I agree with a lot of what you pointed out here but unfortunately I don't have the time to address most of these. However, I think most of the foundation is there to add any of the things you pointed out without much complexity. 

Few notes to point out around a few questions for future context:

- One note around the limitations around infection damage comes from needing to find a spell to cast against the players -- I tried to find one that was deadly all the time so it couldn't be ignored. 

- Post battle royale teleporting is linked to the player's hearthstone.

**Comment by asfo** [comment]
@pygnode I think with the quest fully working, this is marked as ready. The others are just "plus things".

I will try to learn some C++ and will try to add some of the comments and will leave a PR to help this event be even more awesome :) ...

For now I just have to say Thank you again for your support 👍
