### ISSUE TITLE
[Crash] Critical issue

### ISSUE THREAD

**Issue by asfo** [pygnode/Battle-Royale#7]
Hi @pygnode sorry to disturb you again but I found a critical issue which again, I tried to fix, but again I failed.

There is an issue that if more than the limit of the players join the queue or whatever, the server crashes.

Let's say that for example if I have 2 as limit, and then, there is another one who tried to join the server crashes.

I tough that if the third one tries to join there is a message that says "Sorry, not enough space" (or something like that) and tried to fix it in that function but I was unable.

So, if you can help me, this happens if the Teleport is used or directly someone goes to Moonglade.

Thanks in advance!

**Comment by asfo** [comment]
@pygnode ping... :( after months I'm still trying to fix it but not able to, hope you have time if not, will continue trying.

**Comment by asfo** [comment]
After months of trying to fix this I finally know what happened, the player can't be resurrected if is not death, there was requiring a conditional to check that.

Will close this ATM

**Comment by pygnode** [comment]
Sorry for the delay! Excellent find on not being able to resurrect players if they're not dead! Feel free to put a PR in.
